server:
  port: "8080"
  mode: "production" # production or debug
  admin_username: "admin"
  admin_password: "change-this-password"

apps:
  - id: "default"
    name: "Default"
    ticket_url: "http://localhost:8000/api/internal/ws/validate-ticket"
    secret: "super-secret-internal-key"

  - id: "laravel-app-2"
    name: "Laravel App 2"
    ticket_url: "https://api.app2.com/api/internal/ws/validate-ticket"
    secret: "super-secret-key-2"
